In [1]:
import pandas as pd

from src.config import orders, customers, items, reviews, products, sellers, payments, geolocation, PASTA_DADOS, DADOS_TRATADO

pd.set_option('display.max_columns', 100)

In [2]:
df_orders = pd.read_csv(orders)

df_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [3]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [4]:
df_orders["order_status"].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [5]:
df_orders["order_status"]= pd.Categorical(df_orders["order_status"], ordered=False)

In [6]:
df_orders['order_purchase_timestamp'] = pd.to_datetime(df_orders['order_purchase_timestamp'])

In [7]:
df_orders['order_approved_at'] = pd.to_datetime(df_orders['order_approved_at'])

In [8]:
df_orders['order_delivered_carrier_date'] = pd.to_datetime(df_orders['order_delivered_carrier_date'])

In [9]:
df_orders['order_delivered_customer_date'] = pd.to_datetime(df_orders['order_delivered_customer_date'])

In [10]:
df_orders['order_estimated_delivery_date'] = pd.to_datetime(df_orders['order_estimated_delivery_date'])

In [11]:
df_orders['order_id'] = df_orders['order_id'].astype("string")

In [12]:
df_orders['customer_id'] = df_orders['customer_id'].astype("string")

In [13]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  string
 1   customer_id                    99441 non-null  string
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: category(1), datetime64[ns](5), string(2)
memory usage: 5.4 MB

In [14]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [15]:
df_customers = pd.read_csv(customers)

df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [16]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [17]:
df_customers['customer_id'] = df_customers['customer_id'].astype("string")
df_customers['customer_unique_id'] = df_customers['customer_unique_id'].astype("string")
df_customers['customer_city'] = df_customers['customer_city'].astype("string")
df_customers['customer_state'] = df_customers['customer_state'].astype("string")
df_customers['customer_zip_code_prefix'] = df_customers['customer_zip_code_prefix'].astype("string")

In [18]:
df = pd.merge(df_orders, df_customers, on="customer_id", how="left")

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  string
 1   customer_id                    99441 non-null  string
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   customer_unique_id             99441 non-null  string
 9   customer_zip_code_prefix       99441 non-null  string
 10  customer_city                  99441 non-null  string
 11  customer_state                 99441 non-null  string
dtypes: category(1), datetime64[ns](5), string(6)
memory usage: 8.4 MB

In [20]:
df_items = pd.read_csv(items)

df_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [21]:
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [22]:
df_items.nunique()

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

In [23]:
df_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [24]:
df_items['order_id'] = df_items['order_id'].astype("string")
df_items['product_id'] = df_items['product_id'].astype("string")
df_items['seller_id'] = df_items['seller_id'].astype("string")
df_items['shipping_limit_date'] = pd.to_datetime(df_items['shipping_limit_date'])

In [25]:
df = pd.merge(df, df_items, on="order_id", how="left")

In [26]:
df.head(100)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2711a938db643b3f0b62ee2c8a2784aa,29cb486c739f9774c8eb542e07b56cd2,delivered,2017-12-22 00:17:37,2017-12-23 02:15:31,2017-12-27 19:54:46,2018-01-09 19:52:32,2018-01-19,2ae3c67452283d5a0d30b32e0d33296e,71505,brasilia,DF,1.0,ad1128daf194f4b6ac4256e16233497c,1ca7077d890b907f89be8c954a02686a,2017-12-29 02:15:31,45.00,14.10
96,3bc77ce8be27211bac313c2daa402d1a,bf141bf67fbe428d558bcf0e018eab60,delivered,2017-04-06 22:39:29,2017-04-06 22:50:24,2017-04-07 14:54:18,2017-04-11 12:31:36,2017-04-27,c756e1910755edd88c00ac3f46baba4b,31255,belo horizonte,MG,1.0,f497ba62f1d6b4f6a3a3266fa8623ad3,6df688df543f90e9b38f4319e75a9d88,2017-04-12 22:50:24,58.20,8.78
97,10c320f977c6a18f91b2d14be13128c6,b673f0597cb0c4d12778f731045f361a,delivered,2017-05-09 20:48:59,2017-05-09 21:02:45,2017-05-10 11:22:15,2017-05-18 13:22:35,2017-06-01,04e495a3f45df8b41be2e934bbc16961,94055,gravatai,RS,1.0,b3be1f83cef05668c25e134852d44545,3b15288545f8928d3e65a8f949a28291,2017-05-16 21:02:45,110.99,21.27
98,0a4a2fccb27bd83a892fa503987a595b,6772a0a230a2667d16c3620f000e1348,delivered,2017-04-20 20:42:44,2017-04-20 20:55:09,2017-04-25 08:23:08,2017-05-11 13:07:46,2017-05-25,c7a9a76a4b24a7e7b2caff982409b7ee,58600,santa luzia,PB,1.0,f7d7b5c58704fb359a74580622800051,4a3ca9315b744ce9f8e9374361493884,2017-04-28 20:55:09,38.50,24.84
99,e4de6d53ecff736bc68804b0b6e9f635,9f6618c17568ac301465fe7ad056c674,delivered,2017-10-16 14:56:50,2017-10-17 03:49:34,2017-10-27 22:14:21,2017-11-08 21:25:24,2017-11-21,e3bcfea9bab07b492391664fc1ffc28a,44180,antonio cardoso,BA,1.0,90b58782fdd04cb829667fcc41fb65f5,7c67e1448b00f6e969d365cea6b010ab,2017-10-27 03:49:34,179.99,51.13

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  string
 1   customer_id                    113425 non-null  string
 2   order_status                   113425 non-null  category
 3   order_purchase_timestamp       113425 non-null  datetime64[ns]
 4   order_approved_at              113264 non-null  datetime64[ns]
 5   order_delivered_carrier_date   111457 non-null  datetime64[ns]
 6   order_delivered_customer_date  110196 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113425 non-null  datetime64[ns]
 8   customer_unique_id             113425 non-null  string
 9   customer_zip_code_prefix       113425 non-null  string
 10  customer_city                  113425 non-null  string
 11  customer_state                 113425 non-null  string
 12  order_item_id                  112650 non-null  float64
 13  product_id                     112650 non-null  string
 14  seller_id                      112650 non-null  string
 15  shipping_limit_date            112650 non-null  datetime64[ns]
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
dtypes: category(1), datetime64[ns](6), float64(3), string(8)
memory usage: 14.8 MB

In [28]:
df[df["order_item_id"].isnull()].head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
306,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaT,NaT,2017-12-05,41fc647b8c6bd979b1b6364b60471b50,89288,sao bento do sul,SC,NaN,<NA>,<NA>,NaT,NaN,NaN
671,c272bcd21c287498b4883c7512019702,9582c5bbecc65eb568e2c1d839b5cba1,unavailable,2018-01-31 11:31:37,2018-01-31 14:23:50,NaT,NaT,2018-02-16,0e634b16e4c585acbd7b2e8276ce6677,11701,praia grande,SP,NaN,<NA>,<NA>,NaT,NaN,NaN
791,37553832a3a89c9b2db59701c357ca67,7607cd563696c27ede287e515812d528,unavailable,2017-08-14 17:38:02,2017-08-17 00:15:18,NaT,NaT,2017-09-05,596ed6d7a35890b3fbac54ec01f69685,2318,sao paulo,SP,NaN,<NA>,<NA>,NaT,NaN,NaN
850,d57e15fb07fd180f06ab3926b39edcd2,470b93b3f1cde85550fc74cd3a476c78,unavailable,2018-01-08 19:39:03,2018-01-09 07:26:08,NaT,NaT,2018-02-06,2349bbb558908e0955e98d47dacb7adb,48607,paulo afonso,BA,NaN,<NA>,<NA>,NaT,NaN,NaN
1294,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12,4fa4365000c7090fcb8cad5713c6d3db,1151,sao paulo,SP,NaN,<NA>,<NA>,NaT,NaN,NaN

In [29]:
df = df.dropna()

In [30]:
df["order_item_id"].apply(float.is_integer).all()

np.True_

In [31]:
df['order_item_id'] = pd.to_numeric(df['order_item_id'], downcast='integer')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 110180 entries, 0 to 113424
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       110180 non-null  string
 1   customer_id                    110180 non-null  string
 2   order_status                   110180 non-null  category
 3   order_purchase_timestamp       110180 non-null  datetime64[ns]
 4   order_approved_at              110180 non-null  datetime64[ns]
 5   order_delivered_carrier_date   110180 non-null  datetime64[ns]
 6   order_delivered_customer_date  110180 non-null  datetime64[ns]
 7   order_estimated_delivery_date  110180 non-null  datetime64[ns]
 8   customer_unique_id             110180 non-null  string
 9   customer_zip_code_prefix       110180 non-null  string
 10  customer_city                  110180 non-null  string
 11  customer_state                 110180 non-null  string
 12  order_item_id                  110180 non-null  int8
 13  product_id                     110180 non-null  string
 14  seller_id                      110180 non-null  string
 15  shipping_limit_date            110180 non-null  datetime64[ns]
 16  price                          110180 non-null  float64
 17  freight_value                  110180 non-null  float64
dtypes: category(1), datetime64[ns](6), float64(2), int8(1), string(8)
memory usage: 14.5 MB

In [33]:
df_products = pd.read_csv(products)

df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [34]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [35]:
df_products= df_products.dropna()

In [36]:
df_products['product_id'] = df_products['product_id'].astype("string")
df_products['product_category_name'] = pd.Categorical(df_products['product_category_name'], ordered=False)

In [37]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32340 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32340 non-null  string
 1   product_category_name       32340 non-null  category
 2   product_name_lenght         32340 non-null  float64
 3   product_description_lenght  32340 non-null  float64
 4   product_photos_qty          32340 non-null  float64
 5   product_weight_g            32340 non-null  float64
 6   product_length_cm           32340 non-null  float64
 7   product_height_cm           32340 non-null  float64
 8   product_width_cm            32340 non-null  float64
dtypes: category(1), float64(7), string(1)
memory usage: 2.3 MB

In [38]:
df = pd.merge(df, df_products, on="product_id", how="left")
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110180 entries, 0 to 110179
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       110180 non-null  string
 1   customer_id                    110180 non-null  string
 2   order_status                   110180 non-null  category
 3   order_purchase_timestamp       110180 non-null  datetime64[ns]
 4   order_approved_at              110180 non-null  datetime64[ns]
 5   order_delivered_carrier_date   110180 non-null  datetime64[ns]
 6   order_delivered_customer_date  110180 non-null  datetime64[ns]
 7   order_estimated_delivery_date  110180 non-null  datetime64[ns]
 8   customer_unique_id             110180 non-null  string
 9   customer_zip_code_prefix       110180 non-null  string
 10  customer_city                  110180 non-null  string
 11  customer_state                 110180 non-null  string
 12  order_item_id                  110180 non-null  int8
 13  product_id                     110180 non-null  string
 14  seller_id                      110180 non-null  string
 15  shipping_limit_date            110180 non-null  datetime64[ns]
 16  price                          110180 non-null  float64
 17  freight_value                  110180 non-null  float64
 18  product_category_name          108643 non-null  category
 19  product_name_lenght            108643 non-null  float64
 20  product_description_lenght     108643 non-null  float64
 21  product_photos_qty             108643 non-null  float64
 22  product_weight_g               108643 non-null  float64
 23  product_length_cm              108643 non-null  float64
 24  product_height_cm              108643 non-null  float64
 25  product_width_cm               108643 non-null  float64
dtypes: category(2), datetime64[ns](6), float64(9), int8(1), string(8)
memory usage: 19.7 MB

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110180 entries, 0 to 110179
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       110180 non-null  string
 1   customer_id                    110180 non-null  string
 2   order_status                   110180 non-null  category
 3   order_purchase_timestamp       110180 non-null  datetime64[ns]
 4   order_approved_at              110180 non-null  datetime64[ns]
 5   order_delivered_carrier_date   110180 non-null  datetime64[ns]
 6   order_delivered_customer_date  110180 non-null  datetime64[ns]
 7   order_estimated_delivery_date  110180 non-null  datetime64[ns]
 8   customer_unique_id             110180 non-null  string
 9   customer_zip_code_prefix       110180 non-null  string
 10  customer_city                  110180 non-null  string
 11  customer_state                 110180 non-null  string
 12  order_item_id                  110180 non-null  int8
 13  product_id                     110180 non-null  string
 14  seller_id                      110180 non-null  string
 15  shipping_limit_date            110180 non-null  datetime64[ns]
 16  price                          110180 non-null  float64
 17  freight_value                  110180 non-null  float64
 18  product_category_name          108643 non-null  category
 19  product_name_lenght            108643 non-null  float64
 20  product_description_lenght     108643 non-null  float64
 21  product_photos_qty             108643 non-null  float64
 22  product_weight_g               108643 non-null  float64
 23  product_length_cm              108643 non-null  float64
 24  product_height_cm              108643 non-null  float64
 25  product_width_cm               108643 non-null  float64
dtypes: category(2), datetime64[ns](6), float64(9), int8(1), string(8)
memory usage: 19.7 MB

In [41]:
df_sellers = pd.read_csv(sellers)

df_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [42]:
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [43]:
df_sellers['seller_id'] = df_sellers['seller_id'].astype("string")
df_sellers['seller_city'] = df_sellers['seller_city'].astype("string")
df_sellers['seller_state'] = df_sellers['seller_state'].astype("string")
df_sellers['seller_zip_code_prefix'] = df_sellers['seller_zip_code_prefix'].astype("string")

In [44]:
df = pd.merge(df, df_sellers, on="seller_id", how="left")
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570,belo horizonte,SP
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840,guariba,SP
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0,31842,belo horizonte,MG
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0,8752,mogi das cruzes,SP

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110180 entries, 0 to 110179
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       110180 non-null  string
 1   customer_id                    110180 non-null  string
 2   order_status                   110180 non-null  category
 3   order_purchase_timestamp       110180 non-null  datetime64[ns]
 4   order_approved_at              110180 non-null  datetime64[ns]
 5   order_delivered_carrier_date   110180 non-null  datetime64[ns]
 6   order_delivered_customer_date  110180 non-null  datetime64[ns]
 7   order_estimated_delivery_date  110180 non-null  datetime64[ns]
 8   customer_unique_id             110180 non-null  string
 9   customer_zip_code_prefix       110180 non-null  string
 10  customer_city                  110180 non-null  string
 11  customer_state                 110180 non-null  string
 12  order_item_id                  110180 non-null  int8
 13  product_id                     110180 non-null  string
 14  seller_id                      110180 non-null  string
 15  shipping_limit_date            110180 non-null  datetime64[ns]
 16  price                          110180 non-null  float64
 17  freight_value                  110180 non-null  float64
 18  product_category_name          108643 non-null  category
 19  product_name_lenght            108643 non-null  float64
 20  product_description_lenght     108643 non-null  float64
 21  product_photos_qty             108643 non-null  float64
 22  product_weight_g               108643 non-null  float64
 23  product_length_cm              108643 non-null  float64
 24  product_height_cm              108643 non-null  float64
 25  product_width_cm               108643 non-null  float64
 26  seller_zip_code_prefix         110180 non-null  string
 27  seller_city                    110180 non-null  string
 28  seller_state                   110180 non-null  string
dtypes: category(2), datetime64[ns](6), float64(9), int8(1), string(11)
memory usage: 22.2 MB

In [46]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
product_category_name            1537
product_name_lenght              1537
product_description_lenght       1537
product_photos_qty               1537
product_weight_g                 1537
product_length_cm                1537
product_height_cm                1537
product_width_cm                 1537
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
dtype: int64

In [47]:
with pd.option_context("display.max_columns", None):
    display(df.head())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570,belo horizonte,SP
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840,guariba,SP
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0,31842,belo horizonte,MG
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0,8752,mogi das cruzes,SP

In [48]:
with pd.option_context("display.max_columns", None):
    display(df[df.product_category_name.isnull()])

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
119,bfe42c22ecbf90bc9f35cf591270b6a7,803ac05904124294f8767894d6da532b,delivered,2018-01-27 22:04:34,2018-01-27 22:16:18,2018-02-03 03:56:00,2018-02-09 20:16:40,2018-02-26,34c58672601f2c6d29db7efd1f6bf958,38650,bonfinopolis de minas,MG,1,71225f49be70df4297892f6a5fa62171,e5a3438891c0bfdb9394643f95273d8e,2018-01-31 22:16:18,27.30,15.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13483,limeira,SP
206,58ac1947c1a9067b9f416cba6d844a3f,ee8e1d37f563ecc11cc4dcb4dfd794c2,delivered,2017-09-13 09:18:50,2017-09-13 13:45:43,2017-09-14 21:20:03,2017-09-21 21:16:17,2017-09-25,5cbf29b2dcf212a6a5d864b887238c72,4842,sao paulo,SP,1,9820e04e332fc450d6fd975befc1bc28,520b493b57809f446cb0a233bb3e25c7,2017-09-19 13:45:43,110.00,14.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11075,santos,SP
258,e22b71f6e4a481445ec4527cb4c405f7,1faf89c8f142db3fca6cf314c51a37b6,delivered,2017-04-22 13:48:18,2017-04-22 14:01:13,2017-04-24 19:08:53,2017-05-02 15:45:27,2017-05-11,1268b060098ed3f22c2e7c34cc72a1a8,38240,itapagipe,MG,1,3bc5164bc7f4be77002d6651da65c98c,6cd68b3ed6d59aaa9fece558ad360c0a,2017-04-27 14:01:13,22.50,11.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31255,belo horizonte,MG
296,a094215e786240fcfefb83d18036a1cd,86acfb656743da0c113d176832c9d535,delivered,2018-02-08 18:56:45,2018-02-08 19:32:18,2018-02-09 21:41:54,2018-02-19 13:28:50,2018-02-22,f5cb81f98962f7504bef1e75579b6dff,13474,americana,SP,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-02-14 19:10:08,122.99,9.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7133,guarulhos,SP
365,6f841dde94727854eaff3f66432c80ea,a9c9532060c9d245f06526c633d2dfba,delivered,2018-01-02 19:20:35,2018-01-02 19:32:22,2018-01-03 17:34:42,2018-01-27 14:27:59,2018-02-05,5f38cc36e507c4d880489be38964af19,27262,volta redonda,RJ,1,c600d7f13104e8db2ca2b9fa78581409,f18112da765e0971ca5d510dec322bdd,2018-01-08 19:32:22,168.90,24.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88351,brusque,SC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109764,1a10e938a1c7d8e5eecc3380f71ca76b,8a81607347c25d881d995d94de6ad824,delivered,2018-07-25 08:58:35,2018-07-26 03:10:20,2018-07-27 11:32:00,2018-08-01 19:28:20,2018-08-10,75fe53e03a8a9797acb680ce8710da8b,27264,volta redonda,RJ,1,8d39a63db6a98e40571f486e0c711cf7,c826c40d7b19f62a09e2d7c5e7295ee2,2018-07-31 03:10:20,127.20,18.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7133,guarulhos,SP
109928,e33865519137f5737444109ae8438633,64b086bdcc54458af3ea3bd838db54a5,delivered,2018-05-28 00:44:06,2018-05-29 03:31:17,2018-05-30 13:13:00,2018-06-01 22:25:39,2018-06-20,82ffeb20040f58e6c008e4402fa6f992,1228,sao paulo,SP,1,e9cbc0910ab050cbd92fbeb051c270ea,f3da5b2ff499efb8d4a6d371d175d7dd,2018-06-06 03:31:06,33.85,8.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2407,sao paulo,SP
109935,f0dd9af88d8ef5a8e4670fbbedaf19c4,30ddb50bd22ee927ebe308ea3da60735,delivered,2017-09-02 20:38:29,2017-09-05 04:24:12,2017-09-14 23:13:41,2017-09-15 14:59:50,2017-09-19,1d627d8a6e1e33ea8eeeb7a17d998660,11045,santos,SP,1,0c877471e35049402bca235e06cb8063,dd7ddc04e1b6c2c614352b383efe2d36,2017-09-12 04:24:12,84.90,15.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3471,sao paulo,SP
109941,272874573723eec18f23c0471927d778,48e080c8001e92ebea2b64e474f91a60,delivered,2017-12-20 23:10:33,2017-12-20 23:29:37,2017-12-21 21:49:35,2017-12-26 22:29:32,2018-01-09,da59579685bd771fdd4f90fb50d28cd3,7240,guarulhos,SP,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2017-12-27 23:29:37,122.99,9.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7133,guarulhos,SP
109958,dff2b9b8d7cfc595836945e1443789c3,2436fb2666a65fbacae82532e797cabf,delivered,2018-07-16 12:59:02,2018-07-17 04:21:00,2018-07-17 15:08:00,2018-07-20 20:41:32,2018-08-07,9b352d0736779ff0e21fcbd59a7141b3,22641,rio de janeiro,RJ,1,bfa0e398bef2d28bb421d42997982cab,46dc3b2cc0980fb8ec44634e21d2718e,2018-07-19 04:21:00,219.99,15.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22240,rio de janeiro,RJ

In [49]:
df_products[df_products.product_category_name.isnull()]

Empty DataFrame
Columns: [product_id, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

Alguns produtos não tem informações sobre categoria e descricao, apenas informação de peso e tamanho.

In [50]:
df=df.dropna()

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108643 entries, 0 to 110179
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       108643 non-null  string
 1   customer_id                    108643 non-null  string
 2   order_status                   108643 non-null  category
 3   order_purchase_timestamp       108643 non-null  datetime64[ns]
 4   order_approved_at              108643 non-null  datetime64[ns]
 5   order_delivered_carrier_date   108643 non-null  datetime64[ns]
 6   order_delivered_customer_date  108643 non-null  datetime64[ns]
 7   order_estimated_delivery_date  108643 non-null  datetime64[ns]
 8   customer_unique_id             108643 non-null  string
 9   customer_zip_code_prefix       108643 non-null  string
 10  customer_city                  108643 non-null  string
 11  customer_state                 108643 non-null  string
 12  order_item_id                  108643 non-null  int8
 13  product_id                     108643 non-null  string
 14  seller_id                      108643 non-null  string
 15  shipping_limit_date            108643 non-null  datetime64[ns]
 16  price                          108643 non-null  float64
 17  freight_value                  108643 non-null  float64
 18  product_category_name          108643 non-null  category
 19  product_name_lenght            108643 non-null  float64
 20  product_description_lenght     108643 non-null  float64
 21  product_photos_qty             108643 non-null  float64
 22  product_weight_g               108643 non-null  float64
 23  product_length_cm              108643 non-null  float64
 24  product_height_cm              108643 non-null  float64
 25  product_width_cm               108643 non-null  float64
 26  seller_zip_code_prefix         108643 non-null  string
 27  seller_city                    108643 non-null  string
 28  seller_state                   108643 non-null  string
dtypes: category(2), datetime64[ns](6), float64(9), int8(1), string(11)
memory usage: 22.7 MB

In [52]:
df.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,shipping_limit_date,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,108643,108643,108643,108643,108643,108643.000000,108643,108643.000000,108643.000000,108643.000000,108643.000000,108643.000000,108643.000000,108643.000000,108643.000000,108643.000000
mean,2018-01-02 21:15:17.881759744,2018-01-03 07:46:53.072540416,2018-01-06 03:55:38.629060352,2018-01-15 08:28:43.203317504,2018-01-26 16:38:54.368528128,1.198632,2018-01-09 11:45:14.375827200,120.085372,19.982591,48.807691,787.319781,2.210810,2095.564178,30.197629,16.588312,23.030467
min,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-10-04 00:00:00,1.000000,2016-09-19 23:11:33,0.850000,0.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,2017-09-15 23:18:58,2017-09-16 12:19:50,2017-09-19 17:44:58.500000,2017-09-27 18:29:42,2017-10-06 00:00:00,1.000000,2017-09-21 22:36:34,39.900000,13.080000,42.000000,348.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,2018-01-22 11:52:53,2018-01-22 19:38:22,2018-01-25 15:13:21,2018-02-05 14:13:22,2018-02-19 00:00:00,1.000000,2018-01-29 13:51:02,74.900000,16.290000,52.000000,603.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,2018-05-06 17:59:04.500000,2018-05-07 16:53:03,2018-05-09 09:52:00,2018-05-16 16:05:52,2018-05-28 00:00:00,1.000000,2018-05-11 16:31:00,134.900000,21.160000,57.000000,987.000000,3.000000,1800.000000,38.000000,20.000000,30.000000
max,2018-08-29 15:00:37,2018-08-29 15:10:26,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-10-25 00:00:00,21.000000,2020-04-09 22:35:08,6735.000000,409.680000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000
std,NaN,NaN,NaN,NaN,NaN,0.708541,NaN,182.039490,15.733505,10.008580,651.346697,1.721835,3744.019308,16.157227,13.433018,11.696960

In [53]:
df.describe(exclude="number")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,product_id,seller_id,shipping_limit_date,product_category_name,seller_zip_code_prefix,seller_city,seller_state
count,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643,108643
unique,95129,95129,2,NaN,NaN,NaN,NaN,NaN,92082,14844,4073,27,31625,2914,NaN,73,2136,588,22
top,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,NaN,NaN,NaN,NaN,NaN,c8460e4251689ba205045f3ea17884a1,22790,sao paulo,SP,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,NaN,cama_mesa_banho,14940,sao paulo,SP
freq,21,21,108636,NaN,NaN,NaN,NaN,NaN,24,145,17119,45814,520,1996,NaN,10952,7600,27156,77484
mean,NaN,NaN,NaN,2018-01-02 21:15:17.881759744,2018-01-03 07:46:53.072540416,2018-01-06 03:55:38.629060352,2018-01-15 08:28:43.203317504,2018-01-26 16:38:54.368528128,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-09 11:45:14.375827200,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-10-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2016-09-19 23:11:33,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,2017-09-15 23:18:58,2017-09-16 12:19:50,2017-09-19 17:44:58.500000,2017-09-27 18:29:42,2017-10-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2017-09-21 22:36:34,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2018-01-22 11:52:53,2018-01-22 19:38:22,2018-01-25 15:13:21,2018-02-05 14:13:22,2018-02-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-29 13:51:02,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2018-05-06 17:59:04.500000,2018-05-07 16:53:03,2018-05-09 09:52:00,2018-05-16 16:05:52,2018-05-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-11 16:31:00,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2018-08-29 15:00:37,2018-08-29 15:10:26,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-10-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2020-04-09 22:35:08,NaN,NaN,NaN,NaN

In [54]:
for col in df.select_dtypes('category').columns:
    df[col] = df[col].cat.remove_unused_categories()

In [55]:
df['order_status'].value_counts()

order_status
delivered    108636
canceled          7
Name: count, dtype: int64

In [56]:
df[df['order_status']== 'canceled']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
3203,1950d777989f6a877539f53795b4c3c3,1bccb206de9f0f25adc6871a1bcf77b2,canceled,2018-02-19 19:48:52,2018-02-19 20:56:05,2018-02-20 19:57:13,2018-03-21 22:03:51,2018-03-09,6a04c8339c44b23e189446216a494569,32071,contagem,MG,1,e435ceb7ced9b8446defd858630454ed,2a61c271b1ac763450d846849783e922,2018-02-23 20:56:05,29.99,14.10,beleza_saude,28.0,792.0,1.0,440.0,20.0,11.0,17.0,9175,santo andre,SP
9700,dabf2b0e35b423f94618bf965fcb7514,5cdec0bb8cbdf53ffc8fdc212cd247c6,canceled,2016-10-09 00:56:52,2016-10-09 13:36:58,2016-10-13 13:36:59,2016-10-16 14:36:59,2016-11-30,2f96790fba243100730c8d1185dd2f25,5846,sao paulo,SP,1,473795a355d29305c3ea6b156833adf5,620c87c171fb2a6dd6e8bb4dec959fc6,2016-10-13 13:36:59,59.90,0.48,perfumaria,36.0,605.0,2.0,100.0,20.0,20.0,20.0,25645,petropolis,RJ
9701,dabf2b0e35b423f94618bf965fcb7514,5cdec0bb8cbdf53ffc8fdc212cd247c6,canceled,2016-10-09 00:56:52,2016-10-09 13:36:58,2016-10-13 13:36:59,2016-10-16 14:36:59,2016-11-30,2f96790fba243100730c8d1185dd2f25,5846,sao paulo,SP,2,7cd29da0653abeb444703cc5a957f479,620c87c171fb2a6dd6e8bb4dec959fc6,2016-10-13 13:36:59,49.90,29.94,beleza_saude,23.0,565.0,1.0,1029.0,20.0,15.0,17.0,25645,petropolis,RJ
64480,770d331c84e5b214bd9dc70a10b829d0,6c57e6119369185e575b36712766b0ef,canceled,2016-10-07 14:52:30,2016-10-07 15:07:10,2016-10-11 15:07:11,2016-10-14 15:07:11,2016-11-29,59a7bb642795ddc85534fbd5f7360334,20091,rio de janeiro,RJ,1,eba7488e1c67729f045ab43fac426f2e,620c87c171fb2a6dd6e8bb4dec959fc6,2016-10-11 15:07:11,249.90,14.03,perfumaria,43.0,259.0,1.0,610.0,22.0,14.0,16.0,25645,petropolis,RJ
65636,8beb59392e21af5eb9547ae1a9938d06,bf609b5741f71697f65ce3852c5d2623,canceled,2016-10-08 20:17:50,2016-10-09 14:34:30,2016-10-14 22:45:26,2016-10-19 18:47:43,2016-11-30,f9af3bfab584769f34c314b222d34263,20091,rio de janeiro,RJ,1,c66def7098f4d87751f40c3a4855ced1,46dc3b2cc0980fb8ec44634e21d2718e,2016-10-13 14:34:31,99.99,11.23,brinquedos,55.0,546.0,1.0,2100.0,22.0,50.0,32.0,22240,rio de janeiro,RJ
102572,65d1e226dfaeb8cdc42f665422522d14,70fc57eeae292675927697fe03ad3ff5,canceled,2016-10-03 21:01:41,2016-10-04 10:18:57,2016-10-25 12:14:28,2016-11-08 10:58:34,2016-11-25,b8b8726af116a5cfb35b0315ecef9172,22770,rio de janeiro,RJ,1,9c7bdf67b06b419aefb93cfdfc96c55d,ed49da7cadefc454d6a67de249eab240,2016-10-21 16:24:43,21.50,14.11,esporte_lazer,25.0,823.0,1.0,476.0,17.0,14.0,14.0,5571,sao paulo,SP
104584,2c45c33d2f9cb8ff8b1c86cc28c11c30,de4caa97afa80c8eeac2ff4c8da5b72e,canceled,2016-10-09 15:39:56,2016-10-10 10:40:49,2016-10-14 10:40:50,2016-11-09 14:53:50,2016-12-08,d93a22bb52bb2f41a7267b8a02370781,88058,florianopolis,SC,1,e24f73b7631ee3fbb2ab700a9acaa258,0cbcee27c791afa0cdcb08587a2013a8,2016-10-14 10:40:50,135.00,18.51,fashion_bolsas_e_acessorios,60.0,1118.0,6.0,2250.0,22.0,15.0,20.0,37410,tres coracoes,MG

Como temos apenas 7 linhas Canceladas, vamos dropar as linhas canceladas e depois excluir a coluna pois ela terá apenas o valor "entrege" para todas as linhas.

In [57]:
df = df[df['order_status'] == 'delivered']

In [58]:
df['order_status'].value_counts()

order_status
delivered    108636
canceled          0
Name: count, dtype: int64

In [59]:
df = df.drop(columns=['order_status'])

In [60]:
df["product_name_lenght"].apply(float.is_integer).all()

np.True_

In [61]:
df['product_name_lenght'] = pd.to_numeric(df['product_name_lenght'], downcast='integer')

In [62]:
df["product_description_lenght"].apply(float.is_integer).all()

np.True_

In [63]:
df['product_description_lenght'] = pd.to_numeric(df['product_description_lenght'], downcast='integer')

In [64]:
df["product_photos_qty"].apply(float.is_integer).all()

np.True_

In [65]:
df['product_photos_qty'] = pd.to_numeric(df['product_photos_qty'], downcast='integer')

In [66]:
df["product_weight_g"].apply(float.is_integer).all()

np.True_

In [67]:
df['product_weight_g'] = pd.to_numeric(df['product_weight_g'], downcast='integer')

In [68]:
df_products["product_length_cm"].apply(float.is_integer).all()

np.True_

In [69]:
df['product_length_cm'] = pd.to_numeric(df['product_length_cm'], downcast='integer')

In [70]:
df["product_height_cm"].apply(float.is_integer).all()

np.True_

In [71]:
df['product_height_cm'] = pd.to_numeric(df['product_height_cm'], downcast='integer')

In [72]:
df["product_width_cm"].apply(float.is_integer).all()

np.True_

In [73]:
df['product_width_cm'] = pd.to_numeric(df['product_width_cm'], downcast='integer')

In [74]:
df.to_parquet(PASTA_DADOS / "olist_tratado.parquet", index=False)

In [75]:
df_tratado = pd.read_parquet(DADOS_TRATADO)

df_tratado.head()

,order_id,customer_id,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40,268,4,500,19,8,13,9350,maua,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29,178,1,400,19,13,19,31570,belo horizonte,SP
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46,232,1,420,24,19,21,14840,guariba,SP
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,59,468,3,450,30,10,20,31842,belo horizonte,MG
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,38,316,4,250,51,15,15,8752,mogi das cruzes,SP

In [76]:
df_tratado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108636 entries, 0 to 108635
Data columns (total 28 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       108636 non-null  string
 1   customer_id                    108636 non-null  string
 2   order_purchase_timestamp       108636 non-null  datetime64[ns]
 3   order_approved_at              108636 non-null  datetime64[ns]
 4   order_delivered_carrier_date   108636 non-null  datetime64[ns]
 5   order_delivered_customer_date  108636 non-null  datetime64[ns]
 6   order_estimated_delivery_date  108636 non-null  datetime64[ns]
 7   customer_unique_id             108636 non-null  string
 8   customer_zip_code_prefix       108636 non-null  string
 9   customer_city                  108636 non-null  string
 10  customer_state                 108636 non-null  string
 11  order_item_id                  108636 non-null  int8
 12  product_id                     108636 non-null  string
 13  seller_id                      108636 non-null  string
 14  shipping_limit_date            108636 non-null  datetime64[ns]
 15  price                          108636 non-null  float64
 16  freight_value                  108636 non-null  float64
 17  product_category_name          108636 non-null  category
 18  product_name_lenght            108636 non-null  int8
 19  product_description_lenght     108636 non-null  int16
 20  product_photos_qty             108636 non-null  int8
 21  product_weight_g               108636 non-null  int32
 22  product_length_cm              108636 non-null  int8
 23  product_height_cm              108636 non-null  int8
 24  product_width_cm               108636 non-null  int8
 25  seller_zip_code_prefix         108636 non-null  string
 26  seller_city                    108636 non-null  string
 27  seller_state                   108636 non-null  string
dtypes: category(1), datetime64[ns](6), float64(2), int16(1), int32(1), int8(6), string(11)
memory usage: 17.1 MB